# scripts/netlify/netlify_build_dashboard.py
import json
import os
import hashlib
from datetime import datetime
from collections import defaultdict

RESULTS_FILE = "data/netlify_results.json"
OUTPUT_FILE = "docs/index.html"

def load_results():
    if not os.path.exists(RESULTS_FILE):
        print(f"Error: {RESULTS_FILE} not found.")
        return []
    with open(RESULTS_FILE, "r", encoding="utf-8") as f:
        return json.load(f)

def get_color(record):
    total = record.get("test_cases", 0) or 0
    passed = record.get("passed", 0) or 0
    failed = record.get("failed", 0) or 0
    errored = record.get("error", 0) or 0
    incomplete = record.get("incomplete", 0) or 0
    skipped = record.get("skipped", 0) or 0
    retry = record.get("retry_count", 0) or 0

    total_calc = passed + failed + errored + incomplete + skipped
    if total_calc != total:
        return "red"

    if passed == total:
        return "yellow" if retry > 0 else "green"

    return "red"

def build_dashboard():
    print(f"=== Dashboard Build Debug ===")
    print(f"RESULTS_FILE: {RESULTS_FILE}")
    print(f"OUTPUT_FILE: {OUTPUT_FILE}")
    
    # Debug password information
    password = os.getenv("REPORT_PASSWORD", "")
    print(f"REPORT_PASSWORD exists: {bool(password)}")
    print(f"REPORT_PASSWORD length: {len(password)}")
    
    password_hash = hashlib.sha256(password.encode()).hexdigest() if password else ""
    print(f"Password hash generated: {password_hash}")
    
    if not password:
        print("::warning::REPORT_PASSWORD not set. Dashboard will have no authentication.")
    else:
        print("::notice::Password authentication is enabled")
    
    results = load_results()
    print(f"Number of results loaded: {len(results)}")
    
    if not results:
        print("No results found.")
        return
        
    # Debug: Show sample result structure
    if results:
        sample = results[0]
        print(f"Sample result keys: {list(sample.keys())}")
        print(f"Sample html_file: {sample.get('html_file', 'N/A')}")
        print(f"Sample project: {sample.get('project', 'N/A')}")
        print(f"Sample test_suite_id: {sample.get('test_suite_id', 'N/A')}")

    # Group data by Project → Test Suite ID → Date
    data = defaultdict(lambda: defaultdict(dict))

    for r in results:
        project = r.get("project", "Unknown")
        suite = r.get("test_suite_id", "Unknown")
        start = r.get("start") or r.get("end")
        if not start:
            continue
        date = datetime.fromisoformat(start.replace("Z", "+00:00")).strftime("%Y.%m.%d")

        # Keep only latest record for the date
        if date not in data[project][suite] or r.get("end", "") > data[project][suite][date].get("end", ""):
            r["color"] = get_color(r)
            data[project][suite][date] = r

    # Debug: Count available URLs
    url_count = 0
    for project in data:
        for suite in data[project]:
            for date in data[project][suite]:
                record = data[project][suite][date]
                if record.get('html_file'):
                    url_count += 1
    print(f"Total URLs in data: {url_count}")

    # Calculate maximum suite name length for adaptive column width
    max_length = 0
    for project in data:
        for suite in data[project]:
            name = suite.replace("Test Suites/", "")
            if len(name) > max_length:
                max_length = len(name)
    left_col_width = max_length * 9 + 16  # approximate pixel width

    # Collect all dates (latest first)
    all_dates = sorted(
        {d for proj in data.values() for suite in proj.values() for d in suite.keys()},
        reverse=True
    )[:365]

    # Build HTML
    html = [
        "<html><head><meta charset='utf-8'><title>QA Automation Report - DEBUG</title>",
        "<style>",
        "body { background-color: #1e1e1e; color: #ddd; font-family: Arial, sans-serif; margin:0; padding:0; }",
        "h1 { color: #fff; padding: 10px 0 10px 16px; margin:0; }",
        "#login-container { display: flex; align-items: center; justify-content: center; height: 100vh; flex-direction: column; }",
        "#login-box { background-color: #2b2b2b; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }",
        "#login-box h2 { margin-top: 0; color: #fff; }",
        "#password-input { width: 250px; padding: 10px; margin: 10px 0; background-color: #1e1e1e; border: 1px solid #444; color: #ddd; border-radius: 4px; }",
        "#login-button { padding: 10px 20px; background-color: #2e7d32; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; }",
        "#login-button:hover { background-color: #1b5e20; }",
        "#error-message { color: #c62828; margin-top: 10px; display: none; }",
        "#dashboard-content { display: none; }",
        "table { border-collapse: collapse; }",
        "th, td { border: 1px solid #444; text-align: center; padding: 6px; }",
        "th { background-color: #2b2b2b; font-weight: bold; position: sticky; top: 0; z-index: 2; }",
        "th::before { content: ''; position: absolute; top: -1px; left: 0; right: 0; height: 1px; background-color: #2b2b2b; }",
        "th:first-child { position: sticky; left: 0; z-index: 4; background-color: #2b2b2b; text-align: left; padding-left: 8px; border-right: 2px solid #444; }",
        "th:first-child::before { content: ''; position: absolute; top: -1px; left: -1px; width: calc(100% + 1px); height: calc(100% + 1px); background-color: #2b2b2b; z-index: -1; }",
        "td.green { background-color: #2e7d32; color: #fff; cursor: pointer; }",
        "td.yellow { background-color: #f9a825; color: #000; cursor: pointer; }",
        "td.red { background-color: #c62828; color: #fff; cursor: pointer; }",
        "td.green:hover, td.yellow:hover, td.red:hover { opacity: 0.8; }",
        "td.empty { background-color: #2b2b2b; color: #666; }",
        "td.project-separator { background-color: #1e1e1e; }",
        f".suite-name {{ position: sticky; left: 0; background-color: #1e1e1e; width: {left_col_width}px; text-align: left; padding-left: 8px; font-weight: normal; z-index:1; border-right: 2px solid #444; }}",
        ".suite-name::before { content: ''; position: absolute; left: -1px; top: 0; width: 1px; bottom: 0; background-color: #1e1e1e; }",
        ".project-header { position: sticky; left: 0; display: table-cell; background-color: #1e1e1e; text-align: left; padding-left: 8px; font-weight: bold; z-index: 1; border-right: 2px solid #444; border-bottom: 2px solid #444; }",
        ".project-header::before { content: ''; position: absolute; left: -1px; top: 0; width: 1px; bottom: 0; background-color: #1e1e1e; }",
        ".table-container { overflow-x: auto; overflow-y: auto; max-height: 90vh; }",
        ".tooltip { position: absolute; display: none; background-color: #2b2b2b; border: 1px solid #444; padding: 10px; border-radius: 4px; z-index: 1000; pointer-events: none; white-space: nowrap; }",
        ".tooltip-row { margin: 3px 0; }",
        ".tooltip-label { font-weight: bold; display: inline-block; width: 100px; }",
        ".test-button { margin: 5px; padding: 8px 12px; background: #555; color: white; border: none; border-radius: 3px; cursor: pointer; font-size: 12px; }",
        ".test-button:hover { background: #666; }",
        ".test-button.success { background: #2e7d32; }",
        ".test-button.warning { background: #f9a825; color: black; }",
        ".test-button.error { background: #c62828; }",
        ".loading { display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background: #2b2b2b; padding: 20px; border-radius: 8px; z-index: 1001; }",
        ".debug-panel { background: #2b2b2b; padding: 15px; margin: 10px; border-radius: 5px; border: 1px solid #444; }",
        ".debug-output { background: #1e1e1e; padding: 10px; border-radius: 3px; font-family: monospace; font-size: 12px; max-height: 200px; overflow-y: auto; }",
        "</style>",
        "<script>",
        f"const PASSWORD_HASH = '{password_hash}';",
        "const data = " + json.dumps(data, default=str) + ";",
        "",
        "// === DEBUG UTILITIES ===",
        "function logSection(title) {",
        "  console.log(`%c=== ${title} ===`, 'background: #222; color: #0f0; padding: 2px 5px;');",
        "}",
        "",
        "// === PASSWORD HANDLING ===",
        "async function hashPassword(password) {",
        "  const msgBuffer = new TextEncoder().encode(password);",
        "  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);",
        "  const hashArray = Array.from(new Uint8Array(hashBuffer));",
        "  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');",
        "}",
        "",
        "async function checkPassword() {",
        "  logSection('PASSWORD CHECK');",
        "  const password = document.getElementById('password-input').value;",
        "  console.log('Input password length:', password.length);",
        "  const hash = await hashPassword(password);",
        "  console.log('Computed hash:', hash);",
        "  console.log('Expected hash:', PASSWORD_HASH);",
        "  console.log('Hash match:', hash === PASSWORD_HASH);",
        "  if (hash === PASSWORD_HASH) {",
        "    sessionStorage.setItem('reportPassword', password);",
        "    document.getElementById('login-container').style.display = 'none';",
        "    document.getElementById('dashboard-content').style.display = 'block';",
        "    console.log('✓ Login successful');",
        "  } else {",
        "    document.getElementById('error-message').style.display = 'block';",
        "    console.log('✗ Login failed');",
        "  }",
        "}",
        "",
        "// === DATA DEBUGGING ===",
        "function debugDataStructure() {",
        "  logSection('DATA STRUCTURE DEBUG');",
        "  console.log('Full data object:', data);",
        "  let urlCount = 0;",
        "  for (const project in data) {",
        "    console.log(`Project: ${project}`);",
        "    for (const suite in data[project]) {",
        "      console.log(`  Suite: ${suite}`);",
        "      for (const date in data[project][suite]) {",
        "        const record = data[project][suite][date];",
        "        console.log(`    Date: ${date}`, record);",
        "        if (record.html_file) urlCount++;",
        "      }",
        "    }",
        "  }",
        "  console.log(`Total URLs in data: ${urlCount}`);",
        "  return urlCount;",
        "}",
        "",
        "// === URL TESTING ===",
        "async function testAllUrls() {",
        "  logSection('TESTING ALL URLs');",
        "  const results = [];",
        "  ",
        "  for (const project in data) {",
        "    for (const suite in data[project]) {",
        "      for (const date in data[project][suite]) {",
        "        const record = data[project][suite][date];",
        "        if (record && record.html_file) {",
        "          const url = record.html_file;",
        "          console.log(`Testing: ${url}`);",
        "          ",
        "          try {",
        "            // Test with HEAD first (faster)",
        "            const headResponse = await fetch(url, { method: 'HEAD', mode: 'no-cors' });",
        "            results.push({",
        "              url: url,",
        "              status: 'HEAD success',",
        "              accessible: true,",
        "              project: project,",
        "              suite: suite,",
        "              date: date",
        "            });",
        "            console.log(`✓ ${url} - HEAD accessible`);",
        "          } catch (headError) {",
        "            // If HEAD fails, try GET",
        "            try {",
        "              const getResponse = await fetch(url, { mode: 'no-cors' });",
        "              results.push({",
        "                url: url,",
        "                status: 'GET success',",
        "                accessible: true,",
        "                project: project,",
        "                suite: suite,",
        "                date: date",
        "              });",
        "              console.log(`✓ ${url} - GET accessible`);",
        "            } catch (getError) {",
        "              results.push({",
        "                url: url,",
        "                status: 'Failed',",
        "                accessible: false,",
        "                error: getError.message,",
        "                project: project,",
        "                suite: suite,",
        "                date: date",
        "              });",
        "              console.log(`✗ ${url} - ${getError.message}`);",
        "            }",
        "          }",
        "          ",
        "          await new Promise(resolve => setTimeout(resolve, 100)); // Rate limiting",
        "        }",
        "      }",
        "    }",
        "  }",
        "  ",
        "  // Summary",
        "  const accessible = results.filter(r => r.accessible).length;",
        "  const failed = results.filter(r => !r.accessible).length;",
        "  console.log(`URL Test Summary: ${accessible} accessible, ${failed} failed`);",
        "  ",
        "  // Show results in debug panel",
        "  const debugOutput = document.getElementById('debug-output');",
        "  if (debugOutput) {",
        "    debugOutput.innerHTML = results.map(r => ",
        "      `${r.accessible ? '✓' : '✗'} ${r.url}<br>${r.accessible ? r.status : 'Error: ' + r.error}`",
        "    ).join('<br><br>');",
        "  }",
        "  ",
        "  return results;",
        "}",
        "",
        "// === SINGLE URL TEST ===",
        "async function testSingleUrl() {",
        "  logSection('TESTING SINGLE URL');",
        "  // Get first available URL",
        "  let testUrl = null;",
        "  let testRecord = null;",
        "  ",
        "  for (const project in data) {",
        "    for (const suite in data[project]) {",
        "      for (const date in data[project][suite]) {",
        "        const record = data[project][suite][date];",
        "        if (record && record.html_file) {",
        "          testUrl = record.html_file;",
        "          testRecord = record;",
        "          break;",
        "        }",
        "      }",
        "      if (testUrl) break;",
        "    }",
        "    if (testUrl) break;",
        "  }",
        "  ",
        "  if (!testUrl) {",
        "    alert('No URLs found in data');",
        "    return;",
        "  }",
        "  ",
        "  console.log('Testing URL:', testUrl);",
        "  console.log('Record:', testRecord);",
        "  ",
        "  try {",
        "    // Try multiple fetch methods",
        "    console.log('Trying fetch with CORS...');",
        "    const response1 = await fetch(testUrl, { mode: 'cors' });",
        "    console.log('CORS fetch:', response1.status, response1.statusText);",
        "    ",
        "    console.log('Trying fetch without CORS...');",
        "    const response2 = await fetch(testUrl, { mode: 'no-cors' });",
        "    console.log('No-CORS fetch:', response2.type);",
        "    ",
        "    console.log('Trying HEAD request...');",
        "    const response3 = await fetch(testUrl, { method: 'HEAD', mode: 'no-cors' });",
        "    console.log('HEAD request:', response3.type);",
        "    ",
        "    alert(`URL test completed for: ${testUrl}\\nCheck console for details`);",
        "  } catch (e) {",
        "    console.error('All fetch methods failed:', e);",
        "    alert(`All fetch methods failed for: ${testUrl}\\nError: ${e.message}`);",
        "  }",
        "}",
        "",
        "// === CONTENT ANALYSIS ===",
        "async function analyzeContent() {",
        "  logSection('CONTENT ANALYSIS');",
        "  let testUrl = null;",
        "  ",
        "  for (const project in data) {",
        "    for (const suite in data[project]) {",
        "      for (const date in data[project][suite]) {",
        "        const record = data[project][suite][date];",
        "        if (record && record.html_file) {",
        "          testUrl = record.html_file;",
        "          break;",
        "        }",
        "      }",
        "      if (testUrl) break;",
        "    }",
        "    if (testUrl) break;",
        "  }",
        "  ",
        "  if (!testUrl) {",
        "    alert('No URLs found');",
        "    return;",
        "  }",
        "  ",
        "  try {",
        "    console.log('Fetching content from:', testUrl);",
        "    const response = await fetch(testUrl);",
        "    console.log('Response status:', response.status, response.statusText);",
        "    console.log('Content-Type:', response.headers.get('content-type'));",
        "    ",
        "    const content = await response.text();",
        "    console.log('Content length:', content.length);",
        "    console.log('First 500 chars:', content.substring(0, 500));",
        "    ",
        "    // Analyze content type",
        "    const isBase64 = /^[A-Za-z0-9+/]*={0,2}$/.test(content.trim());",
        "    const isHTML = content.trim().toLowerCase().startsWith('<!doctype html') || ",
        "                   content.trim().toLowerCase().startsWith('<html');",
        "    const isBinary = content.length > 0 && content.charCodeAt(0) > 127;",
        "    ",
        "    console.log('Content analysis:');",
        "    console.log('  - Is Base64:', isBase64);",
        "    console.log('  - Is HTML:', isHTML);",
        "    console.log('  - Is likely binary:', isBinary);",
        "    console.log('  - First char code:', content.charCodeAt(0));",
        "    ",
        "    alert(`Content analysis complete for: ${testUrl}\\n` +",
        "          `Length: ${content.length}\\n` +",
        "          `Is Base64: ${isBase64}\\n` +",
        "          `Is HTML: ${isHTML}\\n` +",
        "          `Check console for full details`);",
        "  } catch (e) {",
        "    console.error('Content analysis failed:', e);",
        "    alert(`Content analysis failed: ${e.message}`);",
        "  }",
        "}",
        "",
        "// === ENCRYPTION/DECRYPTION ===",
        "async function decryptBytesAES(encryptedBytes, password) {",
        "  logSection('DECRYPTION PROCESS');",
        "  console.log('Encrypted bytes length:', encryptedBytes.length);",
        "  ",
        "  const salt = encryptedBytes.slice(0, 16);",
        "  const nonce = encryptedBytes.slice(16, 28);",
        "  const ciphertext = encryptedBytes.slice(28);",
        "  ",
        "  console.log('Salt length:', salt.length);",
        "  console.log('Nonce length:', nonce.length);",
        "  console.log('Ciphertext length:', ciphertext.length);",
        "",
        "  const enc = new TextEncoder();",
        "  const keyMaterial = await crypto.subtle.importKey(",
        "    'raw',",
        "    enc.encode(password),",
        "    {name: 'PBKDF2'},",
        "    false,",
        "    ['deriveKey']",
        "  );",
        "",
        "  const key = await crypto.subtle.deriveKey(",
        "    { name: 'PBKDF2', salt: salt, iterations: 100000, hash: 'SHA-256' },",
        "    keyMaterial,",
        "    { name: 'AES-GCM', length: 256 },",
        "    false,",
        "    ['decrypt']",
        "  );",
        "",
        "  const decrypted = await crypto.subtle.decrypt({",
        "    name: 'AES-GCM',",
        "    iv: nonce",
        "  }, key, ciphertext);",
        "",
        "  console.log('Decryption successful, output length:', decrypted.byteLength);",
        "  return new Uint8Array(decrypted);",
        "}",
        "",
        "// === MAIN REPORT OPENING ===",
        "async function openReport(project, suite, date) {",
        "  logSection('OPENING REPORT');",
        "  const record = data[project][suite][date];",
        "  if (!record || !record.html_file) {",
        "    console.error('No record or URL found for:', project, suite, date);",
        "    return;",
        "  }",
        "",
        "  const password = sessionStorage.getItem('reportPassword');",
        "  if (!password) {",
        "    alert('Password missing! Please login again.');",
        "    return;",
        "  }",
        "",
        "  showLoading();",
        "  ",
        "  try {",
        "    console.log('Target URL:', record.html_file);",
        "    ",
        "    // Fetch with error handling",
        "    let response;",
        "    try {",
        "      response = await fetch(record.html_file);",
        "      console.log('Fetch response status:', response.status, response.statusText);",
        "      if (!response.ok) throw new Error(`HTTP ${response.status}: ${response.statusText}`);",
        "    } catch (fetchError) {",
        "      console.error('Fetch failed:', fetchError);",
        "      // Try alternative fetch methods",
        "      try {",
        "        console.log('Trying alternative fetch (no-cors)...');",
        "        response = await fetch(record.html_file, { mode: 'no-cors' });",
        "        console.log('Alternative fetch result:', response.type);",
        "      } catch (altError) {",
        "        throw new Error(`All fetch attempts failed: ${fetchError.message}, ${altError.message}`);",
        "      }",
        "    }",
        "    ",
        "    const encryptedData = await response.arrayBuffer();",
        "    const encryptedBytes = new Uint8Array(encryptedData);",
        "    console.log('Received data size:', encryptedBytes.length);",
        "",
        "    // Smart content detection",
        "    const textContent = new TextDecoder().decode(encryptedBytes);",
        "    const isBase64 = /^[A-Za-z0-9+/]*={0,2}$/.test(textContent.trim());",
        "    console.log('Content is Base64:', isBase64);",
        "",
        "    let rawEncryptedBytes;",
        "    if (isBase64) {",
        "      console.log('Decoding Base64 content...');",
        "      try {",
        "        rawEncryptedBytes = new Uint8Array(atob(textContent).split('').map(c => c.charCodeAt(0)));",
        "        console.log('Base64 decoded size:', rawEncryptedBytes.length);",
        "      } catch (e) {",
        "        console.log('Base64 decode failed, using raw bytes');",
        "        rawEncryptedBytes = encryptedBytes;",
        "      }",
        "    } else {",
        "      console.log('Using raw bytes (not Base64)');",
        "      rawEncryptedBytes = encryptedBytes;",
        "    }",
        "",
        "    console.log('Final encrypted bytes for decryption:', rawEncryptedBytes.length);",
        "    ",
        "    if (rawEncryptedBytes.length < 28) {",
        "      throw new Error(`Insufficient data for decryption. Need 28+ bytes, got ${rawEncryptedBytes.length}`);",
        "    }",
        "",
        "    // Decrypt",
        "    const decryptedBytes = await decryptBytesAES(rawEncryptedBytes, password);",
        "    const decryptedText = new TextDecoder().decode(decryptedBytes);",
        "    console.log('Decrypted text length:', decryptedText.length);",
        "",
        "    // Create and open report",
        "    const blob = new Blob([decryptedText], { type: 'text/html' });",
        "    const url = URL.createObjectURL(blob);",
        "    console.log('Opening decrypted report...');",
        "    window.open(url, '_blank');",
        "    ",
        "  } catch (e) {",
        "    console.error('Report opening failed:', e);",
        "    console.error('Full error:', e.stack);",
        "    alert(`Failed to open report: ${e.message}\\nCheck console for full details.`);",
        "  } finally {",
        "    hideLoading();",
        "  }",
        "}",
        "",
        "// === UI UTILITIES ===",
        "function showLoading() {",
        "  document.getElementById('loading').style.display = 'block';",
        "}",
        "",
        "function hideLoading() {",
        "  document.getElementById('loading').style.display = 'none';",
        "}",
        "",
        "function showTooltip(e, project, suite, date) {",
        "  const record = data[project][suite][date];",
        "  if (!record) return;",
        "  const tooltip = document.getElementById('tooltip');",
        "  const start = new Date(record.start);",
        "  const end = new Date(record.end);",
        "  const formatDate = (d) => d.getFullYear().toString().slice(2) + '/' + ",
        "    String(d.getMonth()+1).padStart(2,'0') + '/' + String(d.getDate()).padStart(2,'0') + ' - ' +",
        "    String(d.getHours()).padStart(2,'0') + ':' + String(d.getMinutes()).padStart(2,'0') + ':' + String(d.getSeconds()).padStart(2,'0');",
        "  const totalSeconds = Math.floor(record.duration * 60);",
        "  const minutes = Math.floor(totalSeconds / 60);",
        "  const seconds = totalSeconds % 60;",
        "  const durationStr = String(minutes).padStart(2,'0') + ':' + String(seconds).padStart(2,'0');",
        "  tooltip.innerHTML = `",
        "    <div class='tooltip-row'><span class='tooltip-label'>Profile:</span><strong>${record.profile || 'N/A'}</strong></div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Test Cases:</span>${record.test_cases || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Passed:</span>${record.passed || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Failed:</span>${record.failed || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Error:</span>${record.error || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Incomplete:</span>${record.incomplete || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Skipped:</span>${record.skipped || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Retry:</span>${record.retry_count || 0}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Start:</span>${formatDate(start)}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>End:</span>${formatDate(end)}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>Duration:</span>${durationStr}</div>",
        "    <div class='tooltip-row'><span class='tooltip-label'>URL:</span>${record.html_file || 'N/A'}</div>",
        "  `;",
        "  tooltip.style.display = 'block';",
        "  tooltip.style.left = (e.pageX + 10) + 'px';",
        "  tooltip.style.top = (e.pageY + 10) + 'px';",
        "}",
        "",
        "function hideTooltip() {",
        "  document.getElementById('tooltip').style.display = 'none';",
        "}",
        "",
        "// === INITIALIZATION ===",
        "document.addEventListener('DOMContentLoaded', function() {",
        "  console.log('=== DASHBOARD INITIALIZATION ===');",
        "  console.log('Password hash available:', !!PASSWORD_HASH);",
        "  console.log('Data loaded:', !!data);",
        "  ",
        "  // Auto-run data debug on load",
        "  setTimeout(() => {",
        "    debugDataStructure();",
        "  }, 1000);",
        "  ",
        "  const savedPassword = sessionStorage.getItem('reportPassword');",
        "  if (savedPassword) {",
        "    hashPassword(savedPassword).then(hash => {",
        "      if (hash === PASSWORD_HASH) {",
        "        document.getElementById('login-container').style.display = 'none';",
        "        document.getElementById('dashboard-content').style.display = 'block';",
        "        console.log('Auto-login successful');",
        "      }",
        "    });",
        "  }",
        "  ",
        "  document.getElementById('password-input').addEventListener('keypress', function(e) {",
        "    if (e.key === 'Enter') checkPassword();",
        "  });",
        "});",
        "</script>",
        "</head><body>",
        "<div id='login-container'>",
        "  <div id='login-box'>",
        "    <h2>QA Automation Report - DEBUG</h2>",
        "    <div><input type='password' id='password-input' placeholder='Enter password' autofocus></div>",
        "    <div><button id='login-button' onclick='checkPassword()'>Login</button></div>",
        "    <div id='error-message'>Incorrect password. Please try again.</div>",
        "  </div>",
        "</div>",
        "<div id='dashboard-content'>",
        "<div id='tooltip' class='tooltip'></div>",
        "<div id='loading' class='loading'>Loading report...</div>",
        "<h1>QA Automation Report - DEBUG MODE</h1>",
        "<div class='debug-panel'>",
        "  <h3>Debug Tools</h3>",
        "  <button onclick=\"debugDataStructure()\" class=\"test-button\">Debug Data</button>",
        "  <button onclick=\"testAllUrls()\" class=\"test-button\">Test All URLs</button>",
        "  <button onclick=\"testSingleUrl()\" class=\"test-button\">Test Single URL</button>",
        "  <button onclick=\"analyzeContent()\" class=\"test-button\">Analyze Content</button>",
        "  <button onclick=\"console.clear()\" class=\"test-button warning\">Clear Console</button>",
        "  <div class='debug-output' id='debug-output'>Debug output will appear here...</div>",
        "</div>",
        "<div class='table-container'>",
        "<table>",
        "<tr><th>Test Suite</th>" + "".join(f"<th>{d[5:]}</th>" for d in all_dates) + "</tr>"
    ]

    # Flatten all projects and suites into single table
    for project in sorted(data.keys()):
        html.append(f"<tr><td class='project-header'>{project}</td>" + "<td class='project-separator'></td>" * len(all_dates) + "</tr>")
        for suite in sorted(data[project].keys()):
            display_name = suite.replace("Test Suites/", "")
            html.append(f"<tr><td class='suite-name'>{display_name}</td>")
            for date in all_dates:
                if date in data[project][suite]:
                    record = data[project][suite][date]
                    color = record["color"]
                    passed = record.get("passed", 0)
